### ISSUE TITLE
Private Video To Publish Selected Video

### ISSUE THREAD

**Issue by tamon504** [namleasia/publish-multiple-selected-youtube-videos#1]
is there any option.? or which line need to change to change the script from private video to publish selected in bulk.?

**Comment by namleasia** [comment]
You can change videos from **private** to **public** easily in Youtube studio interface.
- Select your private videos.
- Click Edit dropdown button on the top.
- Click Visibility, and change it to Public.

So I don't think we need script to do that.
My script is used to change videos from Draft to Public, because there are many steps on each videos.

**Comment by tamon504** [comment]
oke thanks bro, but i need to do this manually to avoid detect from youtube so basiclly i need to do this job manually since i will change more than 200 video, anyway thanks for your hard work. Really appreciate it
